[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'npm install -g @antfu/ni'
]

[phases.install]
cmds = [
  'npx pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'npx pnpm exec prisma generate',
  'npx pnpm run build'
]

[start]
cmd = 'npx pnpm start'

[phases.setup.env]
NODE_ENV = "production"
NPM_CONFIG_PREFIX = "/usr/local"