[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'npm config set prefix "/usr/local"'
]

[phases.install]
cmds = [
  '/usr/local/bin/pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  '/usr/local/bin/pnpm exec prisma generate',
  '/usr/local/bin/pnpm run build'
]

[start]
cmd = '/usr/local/bin/pnpm start'

[phases.setup.env]
PATH = "/usr/local/bin:${PATH}"