[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'npm install -g prisma'
]

[phases.install]
cmds = [
  'npx pnpm install --no-frozen-lockfile',
  'chmod -R 777 node_modules/.bin'
]

[phases.build]
cmds = [
  'chmod -R 777 node_modules/.prisma',
  'npx prisma generate',
  'npx pnpm run build'
]

[start]
cmd = 'npx pnpm start'

[phases.setup.env]
NODE_ENV = "production"
PRISMA_SCHEMA_ENGINE_BINARY = "/app/node_modules/.prisma/client/schema-engine"
PRISMA_QUERY_ENGINE_BINARY = "/app/node_modules/.prisma/client/query-engine"
PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"