[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'find / -name pnpm 2>/dev/null > /tmp/pnpm_path',
  'chmod +x $(cat /tmp/pnpm_path)',
  'ln -s $(cat /tmp/pnpm_path) /usr/bin/pnpm'
]

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm exec prisma generate',
  'pnpm run build'
]

[start]
cmd = 'pnpm start'

[phases.setup.env]
NPM_CONFIG_PREFIX = "/usr/local"
PATH = "/usr/local/bin:/usr/bin:${PATH}"