[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'npm install -g prisma'
]

[phases.install]
cmds = [
  'npx pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'mkdir -p node_modules/.prisma',
  'mkdir -p .next',
  'chmod -R 777 node_modules/.prisma node_modules/.bin .next',
  'npx prisma generate',
  'npx pnpm run build'
]

[start]
cmd = 'npx pnpm start'

[phases.setup.env]
NODE_ENV = "production"
PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
PRISMA_GENERATE_SKIP_DUPLICATE = "true"