[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest'
]

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpx prisma generate',
  'pnpm run build'
]

[start]
cmd = 'pnpm start'