[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']
cmds = [
  'npm install -g pnpm@latest',
  'mkdir -p /usr/bin',
  'npm config get prefix > /tmp/npm_prefix',
  'cp $(cat /tmp/npm_prefix)/bin/pnpm /usr/bin/pnpm',
  'chmod +x /usr/bin/pnpm'
]

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm exec prisma generate',
  'pnpm run build'
]

[start]
cmd = 'pnpm start'

[phases.setup.env]
PATH = "/usr/bin:/usr/local/bin:${PATH}"